---
- name: Configure server for maintenance - Saturday @ 00:00
  hosts: sat_00
  remote_user: sysops
  gather_facts: false
  become: yes

  tasks:
  - name: Create flags directory if it dont exist
    file:
      path: /etc/flags
      state: directory

#  - name: Create [DAY]_[HOUR] flag file if it exists
#    file:
#      path: /etc/flags/sat_00
#      state: file

  - name: Remove sat_01 flag file if it exists
    file:
      path: /etc/flags/sat_01
      state: absent

  - name: Remove sun_00 flag file if it exists
    file:
      path: /etc/flags/sun_00
      state: absent

  - name: Remove sun_01 flag file if it exists
    file:
      path: /etc/flags/sun_01
      state: absent

  - name: Create sat_00 flag file
    copy:
      content: "##?## File Managed by ansible\n"
      dest: /etc/flags/sat_00
