---
- name: Debian - Disable IPv6
  hosts: all
  remote_user: sysops
  gather_facts: false
  become: yes

  tasks:
  - name: Create/Modify config file to cause IPv6 to be enabled
    copy:
      content: 'net.ipv6.conf.all.disable_ipv6 = 0'
      dest: /etc/sysctl.d/70-disable-ipv6.conf
    register: file_change

  - name: Reload network stack if config file changed
    command:
      cmd: sysctl -p -f /etc/sysctl.d/70-disable-ipv6.conf
    when: file_change.changed
