---
- name: Debian OS Maint.
  hosts: '{{ my_hosts | default("lab") }}'
  gather_facts: yes
  become: yes

  tasks:
    - name: Update apt cache and Upgrade installed packages if there are newer packages
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
      register: packages_installed

    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      async: 1
      poll: 0
#      when: packages_installed.changed

    - name: Wait for the reboot to complete if there was a change.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
#      when: packages_installed.changed

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
